#
#  Makefile for Week 3
#
build:
	#@scalac week3_ops_memberFuncions.scala -deprecation
	@scalac week3_ops_patternMatching.scala -deprecation

run:
	#@scala memberFunctions
	@scala patternMatching

clean:
	rm *.class