#
#  Makefile for Week 3
#
build:
	#@scalac week3_ops_memberFuncions.scala -deprecation
	#@scalac week3_ops_patternMatching.scala -deprecation
	@scalac assignment3_scratch.scala -deprecation

run:
	#@scala memberFunctions
	#@scala patternMatching
	@scala assignment3

clean:
	rm *.class
