#
#  Makefile for Week 3
#
build:
	#@scalac week3_ops_memberFuncions.scala -deprecation
	#@scalac week3_ops_patternMatching.scala -deprecation
	@scalac week3_bigStepSemantics.scala -deprecation

run:
	#@scala memberFunctions
	#@scala patternMatching
	@scala EvalExprObject

clean:
	rm *.class