#
#  Makefile for Week 5
#
build:
	#@scalac week5_lettuce.scala -deprecation
	@scalac week5_lettuceInterpreter.scala -deprecation

run:
	#@scala lettuceScratch
	@scala lettuceEval

clean:
	rm *.class
