#
#  Makefile for Week 1
#
build:
	@scalac week1_readings_1.scala -deprecation
	@scalac week1_readings_2.scala -deprecation
	@scalac week1_readings_misc.scala -deprecation

run:
	@scala ListMethods
	@scala ArrayMethods
	@scala MapsPractice
	@scala SetsPractice
	@scala functionPractice
	@scala recursionPractice
	@scala loopsToRecursion
	@scala underlineThing

clean:
	rm *.class