#
#  Makefile for week1_readings.scala
#
build:
	@scalac week1_readings_1.scala -deprecation
	@scalac week1_readings_2.scala -deprecation

run:
	@scala ListMethods
	@scala ArrayMethods
	@scala MapsPractice
	@scala SetsPractice
	@scala functionPractice
	@scala recursionPractice
	@scala loopsToRecursion

clean:
	rm *.class